runtime: nodejs18

env_variables:
  DB_USER: "your-db-user"
  DB_PASSWORD: "your-db-password"
  DB_HOST: "your-db-host"
  DB_NAME: "your-db-name"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10