# deploy.yml
name: Deploy to GitHub Pages

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install --no-audit --silent
          npm audit --production --json || true

      - name: Build
        working-directory: ./frontend
        run: |
          npm run build 2> >(grep -v "warning" >&2)
        env:
          NODE_ENV: production
          BASE_URL: /ECshop/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          force_orphan: true